### ISSUE TITLE
Typo in link to .net sdk

### ISSUE THREAD

**Issue by Hunanbean-Collective** [FlaxEngine/FlaxDocs#105]
I attempted to fix a broken link, but it seems i need to clone the whole repo to do so?
[https://github.com/FlaxEngine/FlaxDocs/blob/c8d26bc70962ea9bdc52d12043d84f1cff1df19d/manual/get-started/requirements.md/#L1](https://github.com/FlaxEngine/FlaxDocs/blob/c8d26bc70962ea9bdc52d12043d84f1cff1df19d/manual/get-started/requirements.md/#L1)
the link to the .net sdk starts with ttps:  when of course it should be https:

Perhaps a public Wiki would make more sense

**Comment by mafiesto4** [comment]
Yeah, Flax Docs are not Wiki but open documentation that can be cloned and updated with PRs from the Community. Still far better than Unity or Unreal docs xD

Thanks for spotting and reporting this. Fixed by @Rayumie in #99. I'll trigger docs rebuild to reflect this change.
