### ISSUE TITLE
Remove the snarky comments from the "Flax for X developers" pages.

### ISSUE THREAD

**Issue by MineBill** [FlaxEngine/FlaxDocs#110]
Once i found out about Flax, the first thing i did was to look in the documentation for a starting out guide. However, seeing this:
![image](https://github.com/FlaxEngine/FlaxDocs/assets/30367251/73009557-745e-4aa9-906e-d97da7b7c48c)
left a really bad taste in my mouth. I get that it is a small joke but when it's the first thing a potetional user might see, imho it makes Flax look unprofessional for throwing shade at other engines. These pages should focus on making a great first impression and teaching a new user how to use the engine.

**Comment by plasmarad** [comment]
At the moment, everyone is trashing unity, even unreal.
I personally liked the "savagery" from flax, it made me like flax even more.

**Comment by Withaust** [comment]
I also think that dropping shade on other engines is a bit unprofessional, Flax also have some problems, there are no engines without them.

**Comment by plasmarad** [comment]
The wording could be changed to something like "transitioning from X to flax"

And the yellow text (if it had to stay) it could also be changed to "We guarantee you'll love us"

**Comment by madsfs** [comment]
This cannot stay in a professional game engine. Please get rid of it entirely and all shade like it. We are not here to bring other engines down.

**Comment by mafiesto4** [comment]
Yeah it's time to move on as Flax becomes a popular engine. Fixed in #113
