### ISSUE TITLE
Spelling correction

### ISSUE THREAD

**Issue by Galbi3000** [FlaxEngine/FlaxDocs#19]
In your docs you use "builded" as the past tense of build, this is incorrect. The correct word is "built".
I'd make the corrections myself and submit them but I have never done that sort of thing in GitHub, still rather noob at it other than cloning projects.

**Comment by stefnotch** [comment]
I know, using GitHub for the first time can be a bit intimidating. 

So, if you want to try submitting your own PR and be awesome, the easiest way to do so is to [go to the file in question](https://github.com/FlaxEngine/FlaxDocs/blob/master/manual/editor/advanced/command-line-access.md).

There, make sure that you're on the `master` branch (dropdown, top left corner)
Then, click on the **edit icon** (pencil, top right of the file)
![image](https://user-images.githubusercontent.com/10220080/102721921-0badd480-42fe-11eb-81a4-601014b89ad1.png)

Then, a text editor will pop up where you can fix and improve everything! After you're happy with your tweaks, scroll to the bottom and click on `Propose changes`
![image](https://user-images.githubusercontent.com/10220080/102722027-9f7fa080-42fe-11eb-89ad-3eefcbc591ae.png)

After you've clicked on that, GitHub will take you to a page where you can check out your changes in detail. There, click on `Create pull request`
![image](https://user-images.githubusercontent.com/10220080/102722022-8ecf2a80-42fe-11eb-864a-24745ecfd143.png)

Lastly, give it a title, write a little description and submit that pull request!

**Comment by mafiesto4** [comment]
Fixed in #21.
