### ISSUE TITLE
Typo in FlaxDocs/manual/get-started/editor.md

### ISSUE THREAD

**Issue by realDLPS** [FlaxEngine/FlaxDocs#83]
At the beginning of the editor documentation there is a "these" misspelt as "thesee"

![image](https://user-images.githubusercontent.com/68390971/189085271-0e3c0031-488f-4289-a6c9-27a503fbdbbd.png)

**Comment by mafiesto4** [comment]
Feel free to open PR from your fix: https://github.com/realDLPS/FlaxDocs/commit/ceff7b7c9cfe578b80538c8ec596d909cffa0932
